services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: VehiculeServer
    command: ["dist/VehiculeServer/index.js"]
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: vehicle
      DB_PASSWORD: vehicle
      DB_NAME: vehicle
    depends_on:
      - database
    networks:
      - vehicle-network

  database:
    image: postgis/postgis:16-3.4-alpine
    container_name: vehicle-database
    environment:
      POSTGRES_USER: vehicle
      POSTGRES_PASSWORD: vehicle
      POSTGRES_DB: vehicle
    ports:
      - "5432:5432"
    networks:
      - vehicle-network

  tool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tool
    command: ["dist/src/index.js"]
    tty: true
    environment:
      DB_HOST: vehicle-database
      DB_PORT: 5432
      API_HOST: VehiculeServer
    networks:
      - vehicle-network
    depends_on:
      - server
      - database

networks:
  vehicle-network:
    driver: bridge
